# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://bguan.github.io/plmcbbox"

git_url = "https://github.com/bguan/plmcbbox/tree/master/"

def custom_doc_links(name): return None
