# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_data": "00_pylightning_frcnn.ipynb",
         "CocoDatasetStats": "00_pylightning_frcnn.ipynb",
         "bbox_to_rect": "00_pylightning_frcnn.ipynb",
         "label_for_bbox": "00_pylightning_frcnn.ipynb",
         "overlay_img_bbox": "00_pylightning_frcnn.ipynb",
         "SubCocoDataset": "00_pylightning_frcnn.ipynb",
         "SubCocoDataModule": "00_pylightning_frcnn.ipynb",
         "SubCocoWrapper": "00_pylightning_frcnn.ipynb",
         "iou_calc": "00_pylightning_frcnn.ipynb",
         "accuracy_1img": "00_pylightning_frcnn.ipynb",
         "FRCNN": "00_pylightning_frcnn.ipynb",
         "digest_pred": "00_pylightning_frcnn.ipynb"}

modules = ["pylightning_frcnn.py"]

doc_url = "https://bguan.github.io/plmcbbox"

git_url = "https://github.com/bguan/plmcbbox/tree/master/"

def custom_doc_links(name): return None
