# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_data": "10_subcoco_utils.ipynb",
         "CocoDatasetStats": "10_subcoco_utils.ipynb",
         "empty_list": "10_subcoco_utils.ipynb",
         "load_stats": "10_subcoco_utils.ipynb",
         "box_within_bounds": "10_subcoco_utils.ipynb",
         "SubCocoParser": "10_subcoco_utils.ipynb",
         "is_notebook": "10_subcoco_utils.ipynb",
         "overlay_img_bbox": "10_subcoco_utils.ipynb",
         "bbox_to_rect": "10_subcoco_utils.ipynb",
         "label_for_bbox": "10_subcoco_utils.ipynb",
         "SubCocoDataset": "10_subcoco_utils.ipynb",
         "TargetResize": "10_subcoco_utils.ipynb",
         "SubCocoDataModule": "10_subcoco_utils.ipynb",
         "SubCocoWrapper": "10_subcoco_utils.ipynb",
         "iou_calc": "10_subcoco_utils.ipynb",
         "accuracy_1img": "10_subcoco_utils.ipynb",
         "FRCNN": "10_subcoco_utils.ipynb",
         "digest_pred": "10_subcoco_utils.ipynb",
         "datadir": "30_subcoco_pl.ipynb",
         "froot": "30_subcoco_pl.ipynb",
         "fname": "30_subcoco_pl.ipynb",
         "url": "30_subcoco_pl.ipynb",
         "json_fname": "30_subcoco_pl.ipynb",
         "img_dir": "30_subcoco_pl.ipynb",
         "stats": "30_subcoco_pl.ipynb",
         "parser": "20_subcoco_ivf.ipynb",
         "size": "20_subcoco_ivf.ipynb",
         "train_tfms": "20_subcoco_ivf.ipynb",
         "valid_tfms": "20_subcoco_ivf.ipynb",
         "train_ds": "20_subcoco_ivf.ipynb",
         "valid_ds": "20_subcoco_ivf.ipynb",
         "bs": "20_subcoco_ivf.ipynb",
         "acc_cycs": "20_subcoco_ivf.ipynb",
         "backbone_name": "20_subcoco_ivf.ipynb",
         "model": "20_subcoco_ivf.ipynb",
         "train_dl": "20_subcoco_ivf.ipynb",
         "valid_dl": "20_subcoco_ivf.ipynb",
         "monitor_metric": "20_subcoco_ivf.ipynb",
         "metrics": "20_subcoco_ivf.ipynb",
         "save_model_fname": "20_subcoco_ivf.ipynb",
         "callbacks": "20_subcoco_ivf.ipynb",
         "learn": "20_subcoco_ivf.ipynb",
         "run_training": "30_subcoco_pl.ipynb",
         "save_final": "30_subcoco_pl.ipynb",
         "frcnn_model": "30_subcoco_pl.ipynb"}

modules = ["subcoco_utils.py",
           "subcoco_ivf.py",
           "subcoco_pl.py"]

doc_url = "https://bguan.github.io/mcbbox"

git_url = "https://github.com/bguan/mcbbox/tree/master/"

def custom_doc_links(name): return None
