# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_data": "10_subcoco_utils.ipynb",
         "CocoDatasetStats": "10_subcoco_utils.ipynb",
         "empty_list": "10_subcoco_utils.ipynb",
         "load_stats": "10_subcoco_utils.ipynb",
         "box_within_bounds": "10_subcoco_utils.ipynb",
         "SubCocoParser": "10_subcoco_utils.ipynb",
         "is_notebook": "10_subcoco_utils.ipynb",
         "overlay_img_bbox": "10_subcoco_utils.ipynb",
         "bbox_to_rect": "10_subcoco_utils.ipynb",
         "label_for_bbox": "10_subcoco_utils.ipynb",
         "SubCocoDataset": "10_subcoco_utils.ipynb",
         "TargetResize": "10_subcoco_utils.ipynb",
         "SubCocoDataModule": "10_subcoco_utils.ipynb",
         "SubCocoWrapper": "10_subcoco_utils.ipynb",
         "iou_calc": "10_subcoco_utils.ipynb",
         "accuracy_1img": "10_subcoco_utils.ipynb",
         "FRCNN": "10_subcoco_utils.ipynb",
         "digest_pred": "10_subcoco_utils.ipynb"}

modules = ["subcoco_utils.py",
           "subcoco_ivf.py",
           "subcoco_pl.py"]

doc_url = "https://bguan.github.io/mcbbox"

git_url = "https://github.com/bguan/mcbbox/tree/master/"

def custom_doc_links(name): return None
