# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_data": "10_subcoco_utils.ipynb",
         "fetch_subcoco": "10_subcoco_utils.ipynb",
         "CocoDatasetStats": "10_subcoco_utils.ipynb",
         "empty_list": "10_subcoco_utils.ipynb",
         "load_stats": "10_subcoco_utils.ipynb",
         "is_notebook": "10_subcoco_utils.ipynb",
         "overlay_img_bbox": "10_subcoco_utils.ipynb",
         "bbox_to_rect": "10_subcoco_utils.ipynb",
         "label_for_bbox": "10_subcoco_utils.ipynb",
         "SubCocoWrapper": "10_subcoco_utils.ipynb",
         "iou_calc": "10_subcoco_utils.ipynb",
         "match_true_false_neg": "10_subcoco_utils.ipynb",
         "calc_wavg_F1": "10_subcoco_utils.ipynb",
         "digest_pred": "10_subcoco_utils.ipynb",
         "box_within_bounds": "20_subcoco_ivf.ipynb",
         "SubCocoParser": "20_subcoco_ivf.ipynb",
         "parse_subcoco": "20_subcoco_ivf.ipynb",
         "SaveModelDupBestCallback": "20_subcoco_ivf.ipynb",
         "gen_transforms_and_learner": "20_subcoco_ivf.ipynb",
         "run_training": "30_subcoco_pl.ipynb",
         "save_final": "30_subcoco_pl.ipynb",
         "SubCocoDataset": "30_subcoco_pl.ipynb",
         "TargetResize": "30_subcoco_pl.ipynb",
         "SubCocoDataModule": "30_subcoco_pl.ipynb",
         "FRCNN": "30_subcoco_pl.ipynb"}

modules = ["subcoco_utils.py",
           "subcoco_ivf.py",
           "subcoco_pl.py"]

doc_url = "https://bguan.github.io/mcbbox"

git_url = "https://github.com/bguan/mcbbox/tree/master/"

def custom_doc_links(name): return None
